FUNCTION ZO_FI_0001_WRITE_DOCUMENT_02.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(OBJECTID) TYPE  CDHDR-OBJECTID
*"     REFERENCE(TCODE) TYPE  CDHDR-TCODE
*"     REFERENCE(UTIME) TYPE  CDHDR-UTIME
*"     REFERENCE(UDATE) TYPE  CDHDR-UDATE
*"     REFERENCE(USERNAME) TYPE  CDHDR-USERNAME
*"     REFERENCE(OBJECT_CHANGE_INDICATOR) TYPE  CDHDR-CHANGE_IND
*"       DEFAULT 'U'
*"     REFERENCE(PLANNED_CHANGE_NUMBER) TYPE  CDHDR-PLANCHNGNR DEFAULT
*"       SPACE
*"     REFERENCE(PLANNED_OR_REAL_CHANGES) TYPE  CDHDR-CHANGE_IND
*"       DEFAULT SPACE
*"     REFERENCE(NO_CHANGE_POINTERS) TYPE  CDHDR-CHANGE_IND DEFAULT
*"       SPACE
*"     REFERENCE(UPD_ICDTXT_Z0_FI_0001) TYPE  CDPOS-CHNGIND DEFAULT
*"       SPACE
*"     REFERENCE(N_ZTB_FI_0021) TYPE  ZTB_FI_0021
*"     REFERENCE(O_ZTB_FI_0021) TYPE  ZTB_FI_0021
*"     REFERENCE(UPD_ZTB_FI_0021) TYPE  CDPOS-CHNGIND DEFAULT SPACE
*"  TABLES
*"      ICDTXT_Z0_FI_0001 STRUCTURE  CDTXT
*"----------------------------------------------------------------------




* THIS FILE IS GENERATED. NEVER CHANGE IT MANUALLY, PLEASE! .

  DATA: lv_UPD_ZTB_FI_0021 type CDPOS-CHNGIND.


  CALL FUNCTION 'CHANGEDOCUMENT_OPEN'
    EXPORTING
      OBJECTCLASS             = 'ZO_FI_0001'
      OBJECTID                = OBJECTID
      PLANNED_CHANGE_NUMBER   = PLANNED_CHANGE_NUMBER
      PLANNED_OR_REAL_CHANGES = PLANNED_OR_REAL_CHANGES
    EXCEPTIONS
      SEQUENCE_INVALID        = 1
      OTHERS                  = 2.

  CASE SY-SUBRC.
    WHEN 0.                                   "OK.
    WHEN 1. MESSAGE A600(ZEBGS_MSG) WITH 'SEQUENCE INVALID'.
    WHEN 2. MESSAGE A600(ZEBGS_MSG)  WITH 'OPEN ERROR'.
  ENDCASE.

  IF UPD_ZTB_FI_0021 NE SPACE.
    IF ( O_ZTB_FI_0021 IS INITIAL ) AND
       (  N_ZTB_FI_0021 IS INITIAL ).

      lv_UPD_ZTB_FI_0021 = SPACE.
*     UPD_ZTB_FI_0021 =  lv_UPD_ZTB_FI_0021.
    ENDIF.
  ENDIF.

  IF UPD_ZTB_FI_0021 NE SPACE.
    CALL FUNCTION 'CHANGEDOCUMENT_SINGLE_CASE'
      EXPORTING
        TABLENAME              = 'ZTB_FI_0021'
        WORKAREA_OLD           = O_ZTB_FI_0021
        WORKAREA_NEW           = N_ZTB_FI_0021
        CHANGE_INDICATOR       = UPD_ZTB_FI_0021
        DOCU_DELETE            = ''
        DOCU_INSERT            = ''
        DOCU_DELETE_IF         = ''
        DOCU_INSERT_IF         = ''
      EXCEPTIONS
        NAMETAB_ERROR          = 1
        OPEN_MISSING           = 2
        POSITION_INSERT_FAILED = 3
        OTHERS                 = 4.

    CASE SY-SUBRC.
      WHEN 0.                                "OK.
      WHEN 1. MESSAGE A600(ZEBGS_MSG) WITH 'NAMETAB-ERROR'.
      WHEN 2. MESSAGE A600(ZEBGS_MSG) WITH 'OPEN MISSING'.
      WHEN 3. MESSAGE A600(ZEBGS_MSG) WITH 'INSERT ERROR'.
      WHEN 4. MESSAGE A600(ZEBGS_MSG) WITH 'SINGLE ERROR'.
    ENDCASE.
  ENDIF.

  IF UPD_ICDTXT_Z0_FI_0001 NE SPACE.
     CALL FUNCTION 'CHANGEDOCUMENT_TEXT_CASE'
       TABLES
         TEXTTABLE              = ICDTXT_Z0_FI_0001
       EXCEPTIONS
         OPEN_MISSING           = 1
         POSITION_INSERT_FAILED = 2
         OTHERS                 = 3.

    CASE SY-SUBRC.
      WHEN 0.                                "OK.
      WHEN 1. MESSAGE A600(ZEBGS_MSG) WITH 'OPEN MISSING'.
      WHEN 2. MESSAGE A600(ZEBGS_MSG) WITH 'INSERT ERROR'.
      WHEN 3. MESSAGE A600(ZEBGS_MSG) WITH 'TEXT ERROR'.
    ENDCASE.
  ENDIF.

  CALL FUNCTION 'CHANGEDOCUMENT_CLOSE'
    EXPORTING
      OBJECTCLASS             = 'ZO_FI_0001'
      OBJECTID                = OBJECTID
      DATE_OF_CHANGE          = UDATE
      TIME_OF_CHANGE          = UTIME
      TCODE                   = TCODE
      USERNAME                = USERNAME
      OBJECT_CHANGE_INDICATOR = OBJECT_CHANGE_INDICATOR
      NO_CHANGE_POINTERS      = NO_CHANGE_POINTERS
    EXCEPTIONS
      HEADER_INSERT_FAILED    = 1
      OBJECT_INVALID          = 2
      OPEN_MISSING            = 3
      NO_POSITION_INSERTED    = 4
      OTHERS                  = 5.

  CASE SY-SUBRC.
    WHEN 0.                                   "OK.
    WHEN 1. MESSAGE A600(ZEBGS_MSG) WITH sy-msgv1.
    WHEN 2. MESSAGE A600(ZEBGS_MSG) WITH 'OBJECT INVALID'.
    WHEN 3. MESSAGE A600(ZEBGS_MSG) WITH 'OPEN MISSING'.
*    WHEN 4. MESSAGE A600 WITH 'NO_POSITION_INSERTED'.
* do not abort, if positions are not inserted!!!
    WHEN 5. MESSAGE A600(ZEBGS_MSG) WITH 'CLOSE ERROR'.
  ENDCASE.

ENDFUNCTION.
