FUNCTION-POOL ZGM_EBGS_EXPORT_XLS.          "MESSAGE-ID ..

* INCLUDE LZGM_EBGS_EXPORT_XLSD...           " Local class definition

TABLES: acdoca, t001.
*----------------------------------------------------------------------*
* TYPE-POOLS
*----------------------------------------------------------------------*
TYPE-POOLS: slis, truxs, vrm, abap.


TYPES: BEGIN OF gt_data_type,
         s_compy  TYPE z_fi_i_glaccountlineitem-s_compy,
         s_bussr  TYPE z_fi_i_glaccountlineitem-s_bussr,
         s_psdat  TYPE z_fi_i_glaccountlineitem-s_psdat,
         s_accdc  TYPE z_fi_i_glaccountlineitem-s_accdc,
         s_glact  TYPE z_fi_i_glaccountlineitem-s_glact,
         s_glacln TYPE z_fi_i_glaccountlineitem-s_glacln,
         s_doctxt TYPE z_fi_i_glaccountlineitem-s_doctxt,
         s_amincc TYPE z_fi_i_glaccountlineitem-s_amincc,
         s_comcr  TYPE z_fi_i_glaccountlineitem-s_comcr,
         s_amtgc  TYPE z_fi_i_glaccountlineitem-s_amtgc,
         s_glocr  TYPE z_fi_i_glaccountlineitem-s_glocr,
         s_amttr  TYPE z_fi_i_glaccountlineitem-s_amttr,
         s_trncr  TYPE z_fi_i_glaccountlineitem-s_trncr,
         s_acdoct TYPE z_fi_i_glaccountlineitem-s_acdoct,
         s_postk  TYPE z_fi_i_glaccountlineitem-s_postk,
         s_partb  TYPE z_fi_i_glaccountlineitem-s_partb,
         s_profct TYPE z_fi_i_glaccountlineitem-s_profct,
         s_costc  TYPE z_fi_i_glaccountlineitem-s_costc,
         s_suppl  TYPE z_fi_i_glaccountlineitem-s_suppl,
         s_nsupl  TYPE z_fi_i_glaccountlineitem-s_nsupl,
         s_stblg  TYPE z_fi_i_glaccountlineitem-s_stblg,
         s_offac  TYPE z_fi_i_glaccountlineitem-s_offac,
         s_acdcbu TYPE z_fi_i_glaccountlineitem-s_acdcbu,
         s_cpudt  TYPE z_fi_i_glaccountlineitem-s_cpudt,
         s_clerdt TYPE z_fi_i_glaccountlineitem-s_clerdt,
         s_clrac  TYPE z_fi_i_glaccountlineitem-s_clrac,
         s_ordid  TYPE z_fi_i_glaccountlineitem-s_ordid,
         s_offat  TYPE z_fi_i_glaccountlineitem-s_offat,
         s_conta  TYPE z_fi_i_glaccountlineitem-s_conta,


       END OF gt_data_type.


TYPES: BEGIN OF abap_compdescr,
         length    TYPE i,
         decimals  TYPE i,
         type_kind TYPE abap_typekind,
         name      TYPE abap_compname,
       END OF abap_compdescr.

TYPES:
  BEGIN OF ty_range,
    sign   TYPE char1,
    option TYPE char2,
    low    TYPE string,
    high   TYPE string,
  END OF ty_range.

DATA: r_filter TYPE RANGE OF ty_range.



*----------------------------------------------------------------------*
* Definição de Constantes
*----------------------------------------------------------------------*

CONSTANTS:
            c_msg_erro(26)  TYPE c VALUE 'Não ha registros'.


**********************************************************************
* Declaração de Tabelas internas
**********************************************************************
DATA:
  gt_data    TYPE TABLE OF gt_data_type,
  gt_comp    TYPE TABLE OF abap_compdescr,
  gs_data    TYPE acdoca,
  lv_numb    TYPE p,
  gs_xls_aux TYPE ZEXCEL_S_EXPORT_XLS,
  gv_datum   TYPE sy-datum,
  gv_uzeit   TYPE sy-uzeit.

**********************************************************************
* Declaração de Workáreas
**********************************************************************
DATA:
  wa_fieldcat TYPE lvc_s_fcat,
  wa_layout   TYPE lvc_s_layo.
*
**********************************************************************
* Declaração de Workáreas
**********************************************************************
DATA:
  gt_fieldcat             TYPE slis_t_fieldcat_alv,
  gs_fieldcat             TYPE slis_fieldcat_alv,
  gs_layout               TYPE slis_layout_alv,
  gs_layout_log           TYPE slis_layout_alv,
  gt_event                TYPE slis_t_event,
  gt_listtop              TYPE slis_t_listheader,
  gs_variant              LIKE disvariant,
  lv_date                 TYPE string,
  gs_zexcel_create_entity TYPE ZTA_ES_CCOUNTEBGS.

RANGES: r_ledger  FOR acdoca-rldnr,
        r_compy  FOR acdoca-rbukrs,
        r_glact  FOR acdoca-racct,
        r_psdat  FOR acdoca-sgtxt,
        r_stats  FOR acdoca-sgtxt,
        r_postk  FOR acdoca-bschl,
        r_asingr FOR acdoca-zuonr,
        r_acdoct FOR acdoca-blart,
        r_amincc FOR acdoca-hsl,
        r_txcode FOR acdoca-mwskz,
        r_clerdt FOR acdoca-augdt,
        r_profct FOR acdoca-prctr,
        r_segmt  FOR acdoca-segment,
        r_doctxt FOR acdoca-sgtxt,

        r_conta  FOR acdoca-rmvct,
        r_fintr  FOR acdoca-bttype,
        r_bustr  FOR acdoca-vrgng,
        r_cobtr  FOR acdoca-awtyp,
        r_refdt  FOR acdoca-awsys,
        r_logsy  FOR acdoca-aworg,
        r_refdc  FOR acdoca-awref,
        r_refdo  FOR acdoca-awitem,
        r_refdi  FOR acdoca-awitgrp,
        r_refdg  FOR acdoca-subta,
        r_trxsi  FOR acdoca-xreversing,
        r_isrev  FOR acdoca-xreversed,
        r_rvref  FOR acdoca-aworg_rev,
        r_rvdoc  FOR acdoca-awref_rev,
        r_isset  FOR acdoca-xsettling,
        r_isstl  FOR acdoca-xsettled,
        r_prdct  FOR acdoca-prec_awtyp,
        r_prdco  FOR acdoca-prec_aworg,
        r_prddo  FOR acdoca-prec_awref,
        r_prddi  FOR acdoca-prec_awitem,
        r_prjcc  FOR acdoca-prec_bukrs,
        r_prjfy  FOR acdoca-prec_gjahr,
        r_prdje  FOR acdoca-prec_belnr,
        r_prdji  FOR acdoca-prec_docln,
        r_srdct  FOR acdoca-src_awtyp,
        r_srlog  FOR acdoca-src_awsys.


DATA: r_fdc1   TYPE RANGE OF ty_range,
      r_amtfd1 TYPE RANGE OF ty_range,
      r_fdc2   TYPE RANGE OF ty_range,
      r_amtfd2 TYPE RANGE OF ty_range,
      r_fdc3   TYPE RANGE OF ty_range,
      r_amtfd3 TYPE RANGE OF ty_range,
      r_fdc4   TYPE RANGE OF ty_range,
      r_amtfd4 TYPE RANGE OF ty_range,
      r_fdc5   TYPE RANGE OF ty_range,
      r_amtfd5 TYPE RANGE OF ty_range,
      r_fdc6   TYPE RANGE OF ty_range,
      r_amtfd6 TYPE RANGE OF ty_range,
      r_fdc7   TYPE RANGE OF ty_range,
      r_amtfd7 TYPE RANGE OF ty_range,
      r_fdc8   TYPE RANGE OF ty_range,
      r_amtfd8 TYPE RANGE OF ty_range,
      r_famtg  TYPE RANGE OF ty_range,
      r_grfag  TYPE RANGE OF ty_range,
      r_pcfag  TYPE RANGE OF ty_range,
      r_famtc  TYPE RANGE OF ty_range,
      r_tpvag  TYPE RANGE OF ty_range,
      r_grtpv  TYPE RANGE OF ty_range,
      r_pctpv  TYPE RANGE OF ty_range,
      r_fpvag  TYPE RANGE OF ty_range,
      r_grfpv  TYPE RANGE OF ty_range,
      r_pcfpv  TYPE RANGE OF ty_range,
      r_conoc  TYPE RANGE OF ty_range,
      r_amtoc  TYPE RANGE OF ty_range,
      r_granc  TYPE RANGE OF ty_range,
      r_amtgr  TYPE RANGE OF ty_range,
      r_baseu  TYPE RANGE OF ty_range,
      r_qty    TYPE RANGE OF ty_range,
      r_fqty   TYPE RANGE OF ty_range,
      r_csuni  TYPE RANGE OF ty_range,
      r_valq   TYPE RANGE OF ty_range,
      r_valf   TYPE RANGE OF ty_range,
      r_refqu  TYPE RANGE OF ty_range,
      r_refq   TYPE RANGE OF ty_range,
      r_addq1u TYPE RANGE OF ty_range,
      r_addq1  TYPE RANGE OF ty_range,
      r_addq2u TYPE RANGE OF ty_range,
      r_addq2  TYPE RANGE OF ty_range,
      r_addq3u TYPE RANGE OF ty_range,
      r_addq3  TYPE RANGE OF ty_range,
      r_dbcrd  TYPE RANGE OF ty_range,
      r_fispe  TYPE RANGE OF ty_range,
      r_fisyv  TYPE RANGE OF ty_range,
      r_postd  TYPE RANGE OF ty_range,
      r_docdt  TYPE RANGE OF ty_range,
      r_acdit  TYPE RANGE OF ty_range,
      r_acdcg  TYPE RANGE OF ty_range,
      r_trxdt  TYPE RANGE OF ty_range,
      r_subat  TYPE RANGE OF ty_range,
      r_acdcbu TYPE RANGE OF ty_range,
      r_lchdt  TYPE RANGE OF ty_range,
      r_crtdt  TYPE RANGE OF ty_range,
      r_crdte  TYPE RANGE OF ty_range,
      r_elipc  TYPE RANGE OF ty_range,
      r_orgot  TYPE RANGE OF ty_range,
      r_gact   TYPE RANGE OF ty_range,
      r_altga  TYPE RANGE OF ty_range,
      r_ctcoa  TYPE RANGE OF ty_range,
      r_itmspl TYPE RANGE OF ty_range,
      r_invre  TYPE RANGE OF ty_range,
      r_invfy  TYPE RANGE OF ty_range,
      r_fodt   TYPE RANGE OF ty_range,
      r_invit  TYPE RANGE OF ty_range,

      r_refpo  TYPE RANGE OF ty_range,
      r_purchd TYPE RANGE OF ty_range,
      r_purchi TYPE RANGE OF ty_range,
      r_acctn  TYPE RANGE OF ty_range,
      r_saled  TYPE RANGE OF ty_range,
      r_salei  TYPE RANGE OF ty_range,
      r_prod   TYPE RANGE OF ty_range,
      r_plant  TYPE RANGE OF ty_range,
      r_suppl  TYPE RANGE OF ty_range,
      r_cust   TYPE RANGE OF ty_range.



DATA    r_psdatf TYPE RANGE OF sy-datum.

DATA:
  s_compy_stg  TYPE string,
  s_glact_stg  TYPE string,
  s_ledger_stg TYPE string,
  s_psdat_stg  TYPE string,
  s_status_stg TYPE string,

  ledger       TYPE string,
  s_ledger     TYPE string,
  s_compy      TYPE string,
  s_status     TYPE string,
  s_glact      TYPE string,
  s_psdat      TYPE string,

  s_postk      TYPE string,
  s_asingr     TYPE string,
  s_acdoct     TYPE string,
  s_amincc     TYPE string,
  s_txcode     TYPE string,
  s_clerdt     TYPE string,
  s_profct     TYPE string,
  s_segmt      TYPE string,
  s_doctxt     TYPE string,

  s_conta      TYPE string,
  s_fintr      TYPE string,
  s_bustr      TYPE string,
  s_cobtr      TYPE string,
  s_refdt      TYPE string,
  s_logsy      TYPE string,
  s_refdc      TYPE string,
  s_refdo      TYPE string,
  s_refdi      TYPE string,
  s_refdg      TYPE string,
  s_trxsi      TYPE string,
  s_isrev      TYPE string,
  s_rvref      TYPE string,
  s_rvdoc      TYPE string,
  s_isset      TYPE string,
  s_isstl      TYPE string,
  s_prdct      TYPE string,
  s_prdco      TYPE string,
  s_prddo      TYPE string,
  s_prddi      TYPE string,
  s_prjcc      TYPE string,
  s_prjfy      TYPE string,
  s_prdje      TYPE string,
  s_prdji      TYPE string,
  s_srdct      TYPE string,
  s_srlog      TYPE string,

***************************************
***************************************

  s_srdoc      TYPE string,
  s_srdci      TYPE string,
  s_srdcs      TYPE string,
  s_iscom      TYPE string,
  s_jriei      TYPE string,
  s_jpecr      TYPE string,
  s_orgch      TYPE string,
  s_costc      TYPE string,
  s_funca      TYPE string,
  s_bussr      TYPE string,
  s_partc      TYPE string,
  s_partp      TYPE string,
  s_partf      TYPE string,
  s_partb      TYPE string,
  s_parts      TYPE string,
  s_baltr      TYPE string,
  s_amtbt      TYPE string,
  s_trncr      TYPE string,
  s_amttr      TYPE string,
  s_comcr      TYPE string,
  s_glocr      TYPE string,
  s_amtgc      TYPE string,

  s_fdc1       TYPE string,
  s_amtfd1     TYPE string,
  s_fdc2       TYPE string,
  s_amtfd2     TYPE string,
  s_fdc3       TYPE string,
  s_amtfd3     TYPE string,
  s_fdc4       TYPE string,
  s_amtfd4     TYPE string,
  s_fdc5       TYPE string,
  s_amtfd5     TYPE string,
  s_fdc6       TYPE string,
  s_amtfd6     TYPE string,
  s_fdc7       TYPE string,
  s_amtfd7     TYPE string,
  s_fdc8       TYPE string,
  s_amtfd8     TYPE string,
  s_famtg      TYPE string,
  s_grfag      TYPE string,
  s_pcfag      TYPE string,
  s_famtc      TYPE string,
  s_tpvag      TYPE string,
  s_grtpv      TYPE string,
  s_pctpv      TYPE string,
  s_fpvag      TYPE string,
  s_grfpv      TYPE string,
  s_pcfpv      TYPE string,
  s_conoc      TYPE string,
  s_amtoc      TYPE string,
  s_granc      TYPE string,
  s_amtgr      TYPE string,
  s_baseu      TYPE string,
  s_qty        TYPE string,
  s_fqty       TYPE string,
  s_csuni      TYPE string,
  s_valq       TYPE string,
  s_valf       TYPE string,
  s_refqu      TYPE string,
  s_refq       TYPE string,
  s_addq1u     TYPE string,
  s_addq1      TYPE string,
  s_addq2u     TYPE string,
  s_addq2      TYPE string,
  s_addq3u     TYPE string,
  s_addq3      TYPE string,
  s_dbcrd      TYPE string,
  s_fispe      TYPE string,
  s_fisyv      TYPE string,
  s_postd      TYPE string,
  s_docdt      TYPE string,
  s_acdit      TYPE string,
  s_acdcg      TYPE string,
  s_trxdt      TYPE string,
  s_subat      TYPE string,
  s_acdcbu     TYPE string,
  s_lchdt      TYPE string,
  s_crtdt      TYPE string,
  s_crdte      TYPE string,
  s_elipc      TYPE string,
  s_orgot      TYPE string,
  s_gact       TYPE string,
  s_altga      TYPE string,
  s_ctcoa      TYPE string,
  s_itmspl     TYPE string,
  s_invre      TYPE string,
  s_invfy      TYPE string,
  s_fodt       TYPE string,
  s_invit      TYPE string,

  s_refpo      TYPE string,
  s_purchd     TYPE string,
  s_purchi     TYPE string,
  s_acctn      TYPE string,
  s_saled      TYPE string,
  s_salei      TYPE string,
  s_prod       TYPE string,
  s_plant      TYPE string,
  s_suppl      TYPE string,
  s_cust       TYPE string.
