interface ZIF_EBG_BASE_CONHEC_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZEBG_BASE_CONHEC,
 CREATE_ZEBG_BASE_CONHEC        TYPE /BOBF/ACT_KEY VALUE '0050569773121EEFBBC02F0C4E04286E',
 DELETE_ZEBG_BASE_CONHEC        TYPE /BOBF/ACT_KEY VALUE '0050569773121EEFBBC02F0C4E04A86E',
 LOCK_ZEBG_BASE_CONHEC          TYPE /BOBF/ACT_KEY VALUE '0050569773121EEFBBC02F0C4E03686E',
 SAVE_ZEBG_BASE_CONHEC          TYPE /BOBF/ACT_KEY VALUE '0050569773121EEFBBC02F0C4E05286E',
 UNLOCK_ZEBG_BASE_CONHEC        TYPE /BOBF/ACT_KEY VALUE '0050569773121EEFBBC02F0C4E03A86E',
 UPDATE_ZEBG_BASE_CONHEC        TYPE /BOBF/ACT_KEY VALUE '0050569773121EEFBBC02F0C4E04686E',
 VALIDATE_ZEBG_BASE_CONHEC      TYPE /BOBF/ACT_KEY VALUE '0050569773121EEFBBC02F0C4E04E86E',
      END OF ZEBG_BASE_CONHEC,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZEBG_BASE_CONHEC,
        BEGIN OF LOCK_ZEBG_BASE_CONHEC,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZEBG_BASE_CONHEC,
        BEGIN OF UNLOCK_ZEBG_BASE_CONHEC,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZEBG_BASE_CONHEC,
      END OF ZEBG_BASE_CONHEC,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZEBG_BASE_CONHEC,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '0050569773121EEFBBC02F6A6007886E',
      END OF ZEBG_BASE_CONHEC,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZEBG_BASE_CONHEC,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '0050569773121EEFBBC02F0C4E03486E',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '0050569773121EEFBBC02F0C4E03086E',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '0050569773121EEFBBC02F0C4E04086E',
      END OF ZEBG_BASE_CONHEC,
      BEGIN OF ZEBG_BASE_CONHEC_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0050569773121EEFBBC02F0C4E05886E',
      END OF ZEBG_BASE_CONHEC_LOCK,
      BEGIN OF ZEBG_BASE_CONHEC_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0050569773121EEFBBC02F0C4E05686E',
      END OF ZEBG_BASE_CONHEC_MESSAGE,
      BEGIN OF ZEBG_BASE_CONHEC_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0050569773121EEFBBC02F0C4E05A86E',
      END OF ZEBG_BASE_CONHEC_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZEBG_BASE_CONHEC,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZEBG_BASE_CONHEC,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '0050569773121EEFBBC02F0C4E02686E' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZEBG_BASE_CONHEC' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZEBG_BASE_CONHEC,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '0050569773121EEFBBC02F6A6007A86E',
      END OF ZEBG_BASE_CONHEC,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZEBG_BASE_CONHEC               TYPE /BOBF/OBM_GROUP_KEY VALUE '0050569773121EEFBBC02F6A600D686E',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZEBG_BASE_CONHEC               TYPE /BOBF/OBM_NODE_KEY VALUE '0050569773121EEFBBC02F0C4E02A86E',
 ZEBG_BASE_CONHEC_LOCK          TYPE /BOBF/OBM_NODE_KEY VALUE '0050569773121EEFBBC02F0C4E03286E',
 ZEBG_BASE_CONHEC_MESSAGE       TYPE /BOBF/OBM_NODE_KEY VALUE '0050569773121EEFBBC02F0C4E02E86E',
 ZEBG_BASE_CONHEC_PROPERTY      TYPE /BOBF/OBM_NODE_KEY VALUE '0050569773121EEFBBC02F0C4E03E86E',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZEBG_BASE_CONHEC,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  USERID                         TYPE STRING VALUE 'USERID',
  EMAIL                          TYPE STRING VALUE 'EMAIL',
  FULLNAME                       TYPE STRING VALUE 'FULLNAME',
  ISNEW                          TYPE STRING VALUE 'ISNEW',
  LASTCHANGEDAT                  TYPE STRING VALUE 'LASTCHANGEDAT',
  TOOLNAME                       TYPE STRING VALUE 'TOOLNAME',
  KNOWLEDGE                      TYPE STRING VALUE 'KNOWLEDGE',
  INTEREST                       TYPE STRING VALUE 'INTEREST',
  TRAINNING                      TYPE STRING VALUE 'TRAINNING',
      END OF ZEBG_BASE_CONHEC,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZEBG_BASE_CONHEC,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '0050569773121EEFBBC02F0C4E02C86E',
      END OF ZEBG_BASE_CONHEC,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZEBG_BASE_CONHEC,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE '0050569773121EEFBBC02F6A6007E86E',
      END OF ZEBG_BASE_CONHEC,
    END OF SC_VALIDATION .
endinterface.
